### ISSUE TITLE
App fails on unbinning

### ISSUE THREAD

**Issue by jwilber** [GeraldKimmersdorfer/rtvis22-cde#1]
After decompressing the data, the app hits an error [0] and  perpetually hangs with the message: `Loading & Preparing data - Please wait`

[0]:
 ```
main.105717b52d8d216f3791.bundle.js:2 Uncaught (in promise) TypeError: n.writeTimestamp is not a function
    at main.105717b52d8d216f3791.bundle.js:2:724827
    at Generator.next (<anonymous>)
    at main.105717b52d8d216f3791.bundle.js:2:692040
    at new Promise (<anonymous>)
    at Xt (main.105717b52d8d216f3791.bundle.js:2:691785)
    at xe (main.105717b52d8d216f3791.bundle.js:2:724206)
    at main.105717b52d8d216f3791.bundle.js:2:729129
```

This occurs both on the web-app and with local build. 
I'm using Chrome 123.0.6312.122 (Official Build) (arm64) 

I haven't had the chance to debug yet - if there's a simple solution I'd love to hear! Otherwise I'll return soon.

Thanks and great project! Excited for the future of viz + webgpu

**Comment by stefnotch** [comment]
This error happens because the [`writeTimestamp` function](https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/writeTimestamp) was deprecated and removed from WebGPU



The easiest fix would be to just remove the calls to that function https://github.com/GeraldKimmersdorfer/rtvis22-cde/blob/fc7651ec3d7e868400185d0352ff518e01f67418/src/renderer.ts#L582

The good fix would be to use [the newer API with `GPUQuerySet`s](https://webgpufundamentals.org/webgpu/lessons/webgpu-timing.html)
